name: NebulaMC
version: '${project.version}'
main: dev.kippenboutske.lunarismc.main
api-version: '1.20'
depend: [PlaceholderAPI]
commands:
  broadcast:
    description: Broadcast a message
    aliases: [ bc ]
    permission: lunarispl.broadcast
    permission-message: Missing permissions!
    usage: /broadcast <text>
