name: NebulaMC
version: '${project.version}'
main: dev.kippenboutske.nebulamc.main
api-version: '1.20'
commands:
  lock:
    description: Lock a player to inspect
    aliases: [l]
    permission: nebulaplugin.lock
    permission-message: This command is only for admins and mods
    usage: /lock
  unlock:
    description: Unlock a player (Only use after lock!)
    aliases: [ul]
    permission: nebulaplugin.unlock
    permission-message: Unlocking is only for admins!
    usage: /unlock
  heal:
    description: Heal jezelf
    aliases: [h]
    permission: nebulaplugin.heal
    permission-message: Je kunt dit command niet uitvoeren, je mist permissies.
    usage: /heal
  broadcast:
    description: Broadcast a message
    aliases: [ bc ]
    permission: nebulaplugin.broadcast
    permission-message: Missing permissions!
    usage: /broadcast <text>
